### PR TITLE
Fix for react-native-web

### PR DESCRIPTION
**Pull request by PeterKottas**
This PR makes the package play along nicely with react-native-web. It doesn't add functionality of modifies, it merely removes warnings about unused properties.

### CODE REVIEW

**Comment by PeterKottas** [comment]
PS: I am really hoping to have this release asap as another package that I am fixing relies on this. Namely this one https://github.com/FaridSafi/react-native-gifted-chat . If you need any help with releasing it don't hesitate to ask. I'll be happy to help.

**Comment by hareeqi** [comment]
@PeterKottas this did not work with create-react-app, i am guessing due to the use of decorators which is not part of  the standards anymore. maybe this need to be re-written to something like react-parsed-text

**Comment by PeterKottas** [comment]
Do you mean the change I made broke it? Or the package in general? There is some extra setup that you need to do if you want to run it on plain create-react-app. It's described in https://github.com/necolas/react-native-web/blob/master/website/guides/getting-started.md . The major point is you need to alias react-native for react-native-web

**Comment by PeterKottas** [comment]
As is, this basically just ensures it doesn't throw warnings or exceptions. That's the first step. The actual functionality might need a second look tbh. Hoping to get to that eventually but first I at least want to make that gifted-chat lib work.

**Comment by fbartho** [comment]
Shipping this in the next release!

**Pull request merged**
