### PR TITLE
Pass index of matched string as 2nd parameter to be able to identify …

### PR DESCRIPTION
**Pull request by adrienthiery**
…to identic strings from each other

### CODE REVIEW

**Comment by jamesone** [comment]
@adrienthiery Does this add the functionality for matching multiple instances of a matched regex?

**Comment by adrienthiery** [comment]
Hi @jamesone ,

To be honest, it's been a while and I don't quite remember, but I think so, yes.

It also allows to differentiate 2 instances that match the same pattern, so I would say yes.

**Comment by adrienthiery** [comment]
@jamesone Thinking about it, isn't that just related to your regexp to match all occurences in the string ?

**Comment by sarathxm** [comment]
Kindly merge this PR fast. I need to use it.

**Comment by fbartho** [comment]
Landing this!

**Comment by adrienthiery** [comment]
Better late than never! Thanks @fbartho 🙂

**Pull request merged**
