### PR TITLE
Support url starting with www

### PR DESCRIPTION
**Pull request by kemcake**
I wanted to support url like `www.github.com` also, I could have add it using a patter but I thought it could bu useful for someone else, let me know if you think this is relevant :grin:

### CODE REVIEW

**Comment by jrichardlai** [comment]
@kemcake sorry for the late reply, thanks for the PR. I think this might be good but what you changed might not allow http://www.google.com anymore, can you write a test for it? thanks

**Comment by DavidE2000** [comment]
@jrichardlai  I tested this PR with http://www.bing.com and http://bing.com and it works fine :)

**Comment by kemcake** [comment]
Yes both should work, but agree I should write a test! 

(Sorry I missed the previous reply 🙃)

**Comment by teyou** [comment]
any plan to merge and bump npm version for this?

**Comment by jrichardlai** [comment]
Woops, I was waiting for a test and forgot about it, I'll test it out and merge it then add a test.

**Comment by jrichardlai** [comment]
@teyou available in 0.0.16

**Comment by teyou** [comment]
cool. However, I noticed one issue with Linking.openURL().
seems http:// or https:// is a must
so either this library will auto append "http://" or we have to do it manually in order to open the weburl using LInking.openURL() method.

reference: http://facebook.github.io/react-native/releases/0.34/docs/linking.html#openurl

**Comment by jrichardlai** [comment]
This library is just about parsing a text and doing some action with it it could also replace the text before rendering it. So in this case you will have to append this manually.

**Comment by DavidE2000** [comment]
Thanks for the merge !

**Pull request merged**
